First 10hrs
makeitrealcamp/guides pull request #66
Opened 2021-01-26 16:43 UTC by danielmoralesp

2021-01-26 18:48 UTC, germanescobar requested changes
@danielmoralesp va por muy buen camino, super, te dejé algunos comentarios y falta algo importante, agregar los temas en SUMMARY.md, podemos ponerlos al final por ahora.

2021-02-03 13:55 UTC, danielmoralesp commented on python/README.md
> +Python es un lenguaje de programación, el cual nos sirve para comunicar ideas. Estas ideas son los comandos, los cuales los plasmamos es un documento, y este documento termina llamándose el “programa
Hola, German, listo, ya hice el cambio, en el proximo PRequest se verá reflajado

2021-02-03 13:56 UTC, danielmoralesp commented on python/control-de-flujo.md
> +Los computadores van por un flujo de decisiones cada vez que ejecuta un programa, evaluando condiciones a medida que corre.
Hola, German, listo, ya hice el cambio, en el proximo PRequest se verá reflajado

2021-02-05 19:57 UTC, germanescobar approved these changes

2021-02-05 19:57 UTC, merged